/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Datatypes;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ArrayOfInt extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8285464653494681695L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ArrayOfInt\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"int\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.Integer> values;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ArrayOfInt() {}

  /**
   * All-args constructor.
   * @param values The new value for values
   */
  public ArrayOfInt(java.util.List<java.lang.Integer> values) {
    this.values = values;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return values;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: values = (java.util.List<java.lang.Integer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'values' field.
   * @return The value of the 'values' field.
   */
  public java.util.List<java.lang.Integer> getValues() {
    return values;
  }

  /**
   * Sets the value of the 'values' field.
   * @param value the value to set.
   */
  public void setValues(java.util.List<java.lang.Integer> value) {
    this.values = value;
  }

  /**
   * Creates a new ArrayOfInt RecordBuilder.
   * @return A new ArrayOfInt RecordBuilder
   */
  public static Energistics.Datatypes.ArrayOfInt.Builder newBuilder() {
    return new Energistics.Datatypes.ArrayOfInt.Builder();
  }

  /**
   * Creates a new ArrayOfInt RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ArrayOfInt RecordBuilder
   */
  public static Energistics.Datatypes.ArrayOfInt.Builder newBuilder(Energistics.Datatypes.ArrayOfInt.Builder other) {
    return new Energistics.Datatypes.ArrayOfInt.Builder(other);
  }

  /**
   * Creates a new ArrayOfInt RecordBuilder by copying an existing ArrayOfInt instance.
   * @param other The existing instance to copy.
   * @return A new ArrayOfInt RecordBuilder
   */
  public static Energistics.Datatypes.ArrayOfInt.Builder newBuilder(Energistics.Datatypes.ArrayOfInt other) {
    return new Energistics.Datatypes.ArrayOfInt.Builder(other);
  }

  /**
   * RecordBuilder for ArrayOfInt instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ArrayOfInt>
    implements org.apache.avro.data.RecordBuilder<ArrayOfInt> {

    private java.util.List<java.lang.Integer> values;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Datatypes.ArrayOfInt.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.values)) {
        this.values = data().deepCopy(fields()[0].schema(), other.values);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ArrayOfInt instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Datatypes.ArrayOfInt other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.values)) {
        this.values = data().deepCopy(fields()[0].schema(), other.values);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'values' field.
      * @return The value.
      */
    public java.util.List<java.lang.Integer> getValues() {
      return values;
    }

    /**
      * Sets the value of the 'values' field.
      * @param value The value of 'values'.
      * @return This builder.
      */
    public Energistics.Datatypes.ArrayOfInt.Builder setValues(java.util.List<java.lang.Integer> value) {
      validate(fields()[0], value);
      this.values = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'values' field has been set.
      * @return True if the 'values' field has been set, false otherwise.
      */
    public boolean hasValues() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'values' field.
      * @return This builder.
      */
    public Energistics.Datatypes.ArrayOfInt.Builder clearValues() {
      values = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ArrayOfInt build() {
      try {
        ArrayOfInt record = new ArrayOfInt();
        record.values = fieldSetFlags()[0] ? this.values : (java.util.List<java.lang.Integer>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
