/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Datatypes;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SupportedProtocol extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -112990698036864049L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SupportedProtocol\",\"namespace\":\"Energistics.Datatypes\",\"fields\":[{\"name\":\"protocol\",\"type\":\"int\"},{\"name\":\"protocolVersion\",\"type\":{\"type\":\"record\",\"name\":\"Version\",\"fields\":[{\"name\":\"major\",\"type\":\"int\"},{\"name\":\"minor\",\"type\":\"int\"},{\"name\":\"revision\",\"type\":\"int\"},{\"name\":\"patch\",\"type\":\"int\"}]}},{\"name\":\"role\",\"type\":\"string\"},{\"name\":\"protocolCapabilities\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"DataValue\",\"fields\":[{\"name\":\"item\",\"type\":[\"null\",\"double\",\"float\",\"int\",\"long\",\"string\",{\"type\":\"record\",\"name\":\"ArrayOfDouble\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]},\"boolean\",\"bytes\"]}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int protocol;
  @Deprecated public Energistics.Datatypes.Version protocolVersion;
  @Deprecated public java.lang.CharSequence role;
  @Deprecated public java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue> protocolCapabilities;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SupportedProtocol() {}

  /**
   * All-args constructor.
   * @param protocol The new value for protocol
   * @param protocolVersion The new value for protocolVersion
   * @param role The new value for role
   * @param protocolCapabilities The new value for protocolCapabilities
   */
  public SupportedProtocol(java.lang.Integer protocol, Energistics.Datatypes.Version protocolVersion, java.lang.CharSequence role, java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue> protocolCapabilities) {
    this.protocol = protocol;
    this.protocolVersion = protocolVersion;
    this.role = role;
    this.protocolCapabilities = protocolCapabilities;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return protocol;
    case 1: return protocolVersion;
    case 2: return role;
    case 3: return protocolCapabilities;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: protocol = (java.lang.Integer)value$; break;
    case 1: protocolVersion = (Energistics.Datatypes.Version)value$; break;
    case 2: role = (java.lang.CharSequence)value$; break;
    case 3: protocolCapabilities = (java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'protocol' field.
   * @return The value of the 'protocol' field.
   */
  public java.lang.Integer getProtocol() {
    return protocol;
  }

  /**
   * Sets the value of the 'protocol' field.
   * @param value the value to set.
   */
  public void setProtocol(java.lang.Integer value) {
    this.protocol = value;
  }

  /**
   * Gets the value of the 'protocolVersion' field.
   * @return The value of the 'protocolVersion' field.
   */
  public Energistics.Datatypes.Version getProtocolVersion() {
    return protocolVersion;
  }

  /**
   * Sets the value of the 'protocolVersion' field.
   * @param value the value to set.
   */
  public void setProtocolVersion(Energistics.Datatypes.Version value) {
    this.protocolVersion = value;
  }

  /**
   * Gets the value of the 'role' field.
   * @return The value of the 'role' field.
   */
  public java.lang.CharSequence getRole() {
    return role;
  }

  /**
   * Sets the value of the 'role' field.
   * @param value the value to set.
   */
  public void setRole(java.lang.CharSequence value) {
    this.role = value;
  }

  /**
   * Gets the value of the 'protocolCapabilities' field.
   * @return The value of the 'protocolCapabilities' field.
   */
  public java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue> getProtocolCapabilities() {
    return protocolCapabilities;
  }

  /**
   * Sets the value of the 'protocolCapabilities' field.
   * @param value the value to set.
   */
  public void setProtocolCapabilities(java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue> value) {
    this.protocolCapabilities = value;
  }

  /**
   * Creates a new SupportedProtocol RecordBuilder.
   * @return A new SupportedProtocol RecordBuilder
   */
  public static Energistics.Datatypes.SupportedProtocol.Builder newBuilder() {
    return new Energistics.Datatypes.SupportedProtocol.Builder();
  }

  /**
   * Creates a new SupportedProtocol RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SupportedProtocol RecordBuilder
   */
  public static Energistics.Datatypes.SupportedProtocol.Builder newBuilder(Energistics.Datatypes.SupportedProtocol.Builder other) {
    return new Energistics.Datatypes.SupportedProtocol.Builder(other);
  }

  /**
   * Creates a new SupportedProtocol RecordBuilder by copying an existing SupportedProtocol instance.
   * @param other The existing instance to copy.
   * @return A new SupportedProtocol RecordBuilder
   */
  public static Energistics.Datatypes.SupportedProtocol.Builder newBuilder(Energistics.Datatypes.SupportedProtocol other) {
    return new Energistics.Datatypes.SupportedProtocol.Builder(other);
  }

  /**
   * RecordBuilder for SupportedProtocol instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SupportedProtocol>
    implements org.apache.avro.data.RecordBuilder<SupportedProtocol> {

    private int protocol;
    private Energistics.Datatypes.Version protocolVersion;
    private Energistics.Datatypes.Version.Builder protocolVersionBuilder;
    private java.lang.CharSequence role;
    private java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue> protocolCapabilities;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Datatypes.SupportedProtocol.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.protocol)) {
        this.protocol = data().deepCopy(fields()[0].schema(), other.protocol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.protocolVersion)) {
        this.protocolVersion = data().deepCopy(fields()[1].schema(), other.protocolVersion);
        fieldSetFlags()[1] = true;
      }
      if (other.hasProtocolVersionBuilder()) {
        this.protocolVersionBuilder = Energistics.Datatypes.Version.newBuilder(other.getProtocolVersionBuilder());
      }
      if (isValidValue(fields()[2], other.role)) {
        this.role = data().deepCopy(fields()[2].schema(), other.role);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.protocolCapabilities)) {
        this.protocolCapabilities = data().deepCopy(fields()[3].schema(), other.protocolCapabilities);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SupportedProtocol instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Datatypes.SupportedProtocol other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.protocol)) {
        this.protocol = data().deepCopy(fields()[0].schema(), other.protocol);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.protocolVersion)) {
        this.protocolVersion = data().deepCopy(fields()[1].schema(), other.protocolVersion);
        fieldSetFlags()[1] = true;
      }
      this.protocolVersionBuilder = null;
      if (isValidValue(fields()[2], other.role)) {
        this.role = data().deepCopy(fields()[2].schema(), other.role);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.protocolCapabilities)) {
        this.protocolCapabilities = data().deepCopy(fields()[3].schema(), other.protocolCapabilities);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'protocol' field.
      * @return The value.
      */
    public java.lang.Integer getProtocol() {
      return protocol;
    }

    /**
      * Sets the value of the 'protocol' field.
      * @param value The value of 'protocol'.
      * @return This builder.
      */
    public Energistics.Datatypes.SupportedProtocol.Builder setProtocol(int value) {
      validate(fields()[0], value);
      this.protocol = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'protocol' field has been set.
      * @return True if the 'protocol' field has been set, false otherwise.
      */
    public boolean hasProtocol() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'protocol' field.
      * @return This builder.
      */
    public Energistics.Datatypes.SupportedProtocol.Builder clearProtocol() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'protocolVersion' field.
      * @return The value.
      */
    public Energistics.Datatypes.Version getProtocolVersion() {
      return protocolVersion;
    }

    /**
      * Sets the value of the 'protocolVersion' field.
      * @param value The value of 'protocolVersion'.
      * @return This builder.
      */
    public Energistics.Datatypes.SupportedProtocol.Builder setProtocolVersion(Energistics.Datatypes.Version value) {
      validate(fields()[1], value);
      this.protocolVersionBuilder = null;
      this.protocolVersion = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'protocolVersion' field has been set.
      * @return True if the 'protocolVersion' field has been set, false otherwise.
      */
    public boolean hasProtocolVersion() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'protocolVersion' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public Energistics.Datatypes.Version.Builder getProtocolVersionBuilder() {
      if (protocolVersionBuilder == null) {
        if (hasProtocolVersion()) {
          setProtocolVersionBuilder(Energistics.Datatypes.Version.newBuilder(protocolVersion));
        } else {
          setProtocolVersionBuilder(Energistics.Datatypes.Version.newBuilder());
        }
      }
      return protocolVersionBuilder;
    }

    /**
     * Sets the Builder instance for the 'protocolVersion' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public Energistics.Datatypes.SupportedProtocol.Builder setProtocolVersionBuilder(Energistics.Datatypes.Version.Builder value) {
      clearProtocolVersion();
      protocolVersionBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'protocolVersion' field has an active Builder instance
     * @return True if the 'protocolVersion' field has an active Builder instance
     */
    public boolean hasProtocolVersionBuilder() {
      return protocolVersionBuilder != null;
    }

    /**
      * Clears the value of the 'protocolVersion' field.
      * @return This builder.
      */
    public Energistics.Datatypes.SupportedProtocol.Builder clearProtocolVersion() {
      protocolVersion = null;
      protocolVersionBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'role' field.
      * @return The value.
      */
    public java.lang.CharSequence getRole() {
      return role;
    }

    /**
      * Sets the value of the 'role' field.
      * @param value The value of 'role'.
      * @return This builder.
      */
    public Energistics.Datatypes.SupportedProtocol.Builder setRole(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.role = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'role' field has been set.
      * @return True if the 'role' field has been set, false otherwise.
      */
    public boolean hasRole() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'role' field.
      * @return This builder.
      */
    public Energistics.Datatypes.SupportedProtocol.Builder clearRole() {
      role = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'protocolCapabilities' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue> getProtocolCapabilities() {
      return protocolCapabilities;
    }

    /**
      * Sets the value of the 'protocolCapabilities' field.
      * @param value The value of 'protocolCapabilities'.
      * @return This builder.
      */
    public Energistics.Datatypes.SupportedProtocol.Builder setProtocolCapabilities(java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue> value) {
      validate(fields()[3], value);
      this.protocolCapabilities = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'protocolCapabilities' field has been set.
      * @return True if the 'protocolCapabilities' field has been set, false otherwise.
      */
    public boolean hasProtocolCapabilities() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'protocolCapabilities' field.
      * @return This builder.
      */
    public Energistics.Datatypes.SupportedProtocol.Builder clearProtocolCapabilities() {
      protocolCapabilities = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public SupportedProtocol build() {
      try {
        SupportedProtocol record = new SupportedProtocol();
        record.protocol = fieldSetFlags()[0] ? this.protocol : (java.lang.Integer) defaultValue(fields()[0]);
        if (protocolVersionBuilder != null) {
          record.protocolVersion = this.protocolVersionBuilder.build();
        } else {
          record.protocolVersion = fieldSetFlags()[1] ? this.protocolVersion : (Energistics.Datatypes.Version) defaultValue(fields()[1]);
        }
        record.role = fieldSetFlags()[2] ? this.role : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.protocolCapabilities = fieldSetFlags()[3] ? this.protocolCapabilities : (java.util.Map<java.lang.CharSequence,Energistics.Datatypes.DataValue>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
