/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Datatypes.Object;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Resource extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3002464562330468779L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Resource\",\"namespace\":\"Energistics.Datatypes.Object\",\"fields\":[{\"name\":\"uri\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"contentType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"channelSubscribable\",\"type\":\"boolean\"},{\"name\":\"customData\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}},{\"name\":\"resourceType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"hasChildren\",\"type\":\"int\"},{\"name\":\"uuid\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"lastChanged\",\"type\":\"long\"},{\"name\":\"objectNotifiable\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String uri;
  @Deprecated public java.lang.String contentType;
  @Deprecated public java.lang.String name;
  @Deprecated public boolean channelSubscribable;
  @Deprecated public java.util.Map<java.lang.String,java.lang.String> customData;
  @Deprecated public java.lang.String resourceType;
  @Deprecated public int hasChildren;
  @Deprecated public java.lang.String uuid;
  @Deprecated public long lastChanged;
  @Deprecated public boolean objectNotifiable;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Resource() {}

  /**
   * All-args constructor.
   * @param uri The new value for uri
   * @param contentType The new value for contentType
   * @param name The new value for name
   * @param channelSubscribable The new value for channelSubscribable
   * @param customData The new value for customData
   * @param resourceType The new value for resourceType
   * @param hasChildren The new value for hasChildren
   * @param uuid The new value for uuid
   * @param lastChanged The new value for lastChanged
   * @param objectNotifiable The new value for objectNotifiable
   */
  public Resource(java.lang.String uri, java.lang.String contentType, java.lang.String name, java.lang.Boolean channelSubscribable, java.util.Map<java.lang.String,java.lang.String> customData, java.lang.String resourceType, java.lang.Integer hasChildren, java.lang.String uuid, java.lang.Long lastChanged, java.lang.Boolean objectNotifiable) {
    this.uri = uri;
    this.contentType = contentType;
    this.name = name;
    this.channelSubscribable = channelSubscribable;
    this.customData = customData;
    this.resourceType = resourceType;
    this.hasChildren = hasChildren;
    this.uuid = uuid;
    this.lastChanged = lastChanged;
    this.objectNotifiable = objectNotifiable;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    case 1: return contentType;
    case 2: return name;
    case 3: return channelSubscribable;
    case 4: return customData;
    case 5: return resourceType;
    case 6: return hasChildren;
    case 7: return uuid;
    case 8: return lastChanged;
    case 9: return objectNotifiable;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.String)value$; break;
    case 1: contentType = (java.lang.String)value$; break;
    case 2: name = (java.lang.String)value$; break;
    case 3: channelSubscribable = (java.lang.Boolean)value$; break;
    case 4: customData = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    case 5: resourceType = (java.lang.String)value$; break;
    case 6: hasChildren = (java.lang.Integer)value$; break;
    case 7: uuid = (java.lang.String)value$; break;
    case 8: lastChanged = (java.lang.Long)value$; break;
    case 9: objectNotifiable = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uri' field.
   * @return The value of the 'uri' field.
   */
  public java.lang.String getUri() {
    return uri;
  }

  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.String value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'contentType' field.
   * @return The value of the 'contentType' field.
   */
  public java.lang.String getContentType() {
    return contentType;
  }

  /**
   * Sets the value of the 'contentType' field.
   * @param value the value to set.
   */
  public void setContentType(java.lang.String value) {
    this.contentType = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'channelSubscribable' field.
   * @return The value of the 'channelSubscribable' field.
   */
  public java.lang.Boolean getChannelSubscribable() {
    return channelSubscribable;
  }

  /**
   * Sets the value of the 'channelSubscribable' field.
   * @param value the value to set.
   */
  public void setChannelSubscribable(java.lang.Boolean value) {
    this.channelSubscribable = value;
  }

  /**
   * Gets the value of the 'customData' field.
   * @return The value of the 'customData' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getCustomData() {
    return customData;
  }

  /**
   * Sets the value of the 'customData' field.
   * @param value the value to set.
   */
  public void setCustomData(java.util.Map<java.lang.String,java.lang.String> value) {
    this.customData = value;
  }

  /**
   * Gets the value of the 'resourceType' field.
   * @return The value of the 'resourceType' field.
   */
  public java.lang.String getResourceType() {
    return resourceType;
  }

  /**
   * Sets the value of the 'resourceType' field.
   * @param value the value to set.
   */
  public void setResourceType(java.lang.String value) {
    this.resourceType = value;
  }

  /**
   * Gets the value of the 'hasChildren' field.
   * @return The value of the 'hasChildren' field.
   */
  public java.lang.Integer getHasChildren() {
    return hasChildren;
  }

  /**
   * Sets the value of the 'hasChildren' field.
   * @param value the value to set.
   */
  public void setHasChildren(java.lang.Integer value) {
    this.hasChildren = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   * @return The value of the 'uuid' field.
   */
  public java.lang.String getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.String value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'lastChanged' field.
   * @return The value of the 'lastChanged' field.
   */
  public java.lang.Long getLastChanged() {
    return lastChanged;
  }

  /**
   * Sets the value of the 'lastChanged' field.
   * @param value the value to set.
   */
  public void setLastChanged(java.lang.Long value) {
    this.lastChanged = value;
  }

  /**
   * Gets the value of the 'objectNotifiable' field.
   * @return The value of the 'objectNotifiable' field.
   */
  public java.lang.Boolean getObjectNotifiable() {
    return objectNotifiable;
  }

  /**
   * Sets the value of the 'objectNotifiable' field.
   * @param value the value to set.
   */
  public void setObjectNotifiable(java.lang.Boolean value) {
    this.objectNotifiable = value;
  }

  /**
   * Creates a new Resource RecordBuilder.
   * @return A new Resource RecordBuilder
   */
  public static Energistics.Datatypes.Object.Resource.Builder newBuilder() {
    return new Energistics.Datatypes.Object.Resource.Builder();
  }

  /**
   * Creates a new Resource RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Resource RecordBuilder
   */
  public static Energistics.Datatypes.Object.Resource.Builder newBuilder(Energistics.Datatypes.Object.Resource.Builder other) {
    return new Energistics.Datatypes.Object.Resource.Builder(other);
  }

  /**
   * Creates a new Resource RecordBuilder by copying an existing Resource instance.
   * @param other The existing instance to copy.
   * @return A new Resource RecordBuilder
   */
  public static Energistics.Datatypes.Object.Resource.Builder newBuilder(Energistics.Datatypes.Object.Resource other) {
    return new Energistics.Datatypes.Object.Resource.Builder(other);
  }

  /**
   * RecordBuilder for Resource instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Resource>
    implements org.apache.avro.data.RecordBuilder<Resource> {

    private java.lang.String uri;
    private java.lang.String contentType;
    private java.lang.String name;
    private boolean channelSubscribable;
    private java.util.Map<java.lang.String,java.lang.String> customData;
    private java.lang.String resourceType;
    private int hasChildren;
    private java.lang.String uuid;
    private long lastChanged;
    private boolean objectNotifiable;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Datatypes.Object.Resource.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contentType)) {
        this.contentType = data().deepCopy(fields()[1].schema(), other.contentType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.channelSubscribable)) {
        this.channelSubscribable = data().deepCopy(fields()[3].schema(), other.channelSubscribable);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customData)) {
        this.customData = data().deepCopy(fields()[4].schema(), other.customData);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.resourceType)) {
        this.resourceType = data().deepCopy(fields()[5].schema(), other.resourceType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.hasChildren)) {
        this.hasChildren = data().deepCopy(fields()[6].schema(), other.hasChildren);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.uuid)) {
        this.uuid = data().deepCopy(fields()[7].schema(), other.uuid);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lastChanged)) {
        this.lastChanged = data().deepCopy(fields()[8].schema(), other.lastChanged);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.objectNotifiable)) {
        this.objectNotifiable = data().deepCopy(fields()[9].schema(), other.objectNotifiable);
        fieldSetFlags()[9] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Resource instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Datatypes.Object.Resource other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contentType)) {
        this.contentType = data().deepCopy(fields()[1].schema(), other.contentType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.channelSubscribable)) {
        this.channelSubscribable = data().deepCopy(fields()[3].schema(), other.channelSubscribable);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.customData)) {
        this.customData = data().deepCopy(fields()[4].schema(), other.customData);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.resourceType)) {
        this.resourceType = data().deepCopy(fields()[5].schema(), other.resourceType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.hasChildren)) {
        this.hasChildren = data().deepCopy(fields()[6].schema(), other.hasChildren);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.uuid)) {
        this.uuid = data().deepCopy(fields()[7].schema(), other.uuid);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.lastChanged)) {
        this.lastChanged = data().deepCopy(fields()[8].schema(), other.lastChanged);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.objectNotifiable)) {
        this.objectNotifiable = data().deepCopy(fields()[9].schema(), other.objectNotifiable);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'uri' field.
      * @return The value.
      */
    public java.lang.String getUri() {
      return uri;
    }

    /**
      * Sets the value of the 'uri' field.
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setUri(java.lang.String value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'uri' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'contentType' field.
      * @return The value.
      */
    public java.lang.String getContentType() {
      return contentType;
    }

    /**
      * Sets the value of the 'contentType' field.
      * @param value The value of 'contentType'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setContentType(java.lang.String value) {
      validate(fields()[1], value);
      this.contentType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'contentType' field has been set.
      * @return True if the 'contentType' field has been set, false otherwise.
      */
    public boolean hasContentType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'contentType' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearContentType() {
      contentType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'channelSubscribable' field.
      * @return The value.
      */
    public java.lang.Boolean getChannelSubscribable() {
      return channelSubscribable;
    }

    /**
      * Sets the value of the 'channelSubscribable' field.
      * @param value The value of 'channelSubscribable'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setChannelSubscribable(boolean value) {
      validate(fields()[3], value);
      this.channelSubscribable = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'channelSubscribable' field has been set.
      * @return True if the 'channelSubscribable' field has been set, false otherwise.
      */
    public boolean hasChannelSubscribable() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'channelSubscribable' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearChannelSubscribable() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'customData' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getCustomData() {
      return customData;
    }

    /**
      * Sets the value of the 'customData' field.
      * @param value The value of 'customData'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setCustomData(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[4], value);
      this.customData = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'customData' field has been set.
      * @return True if the 'customData' field has been set, false otherwise.
      */
    public boolean hasCustomData() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'customData' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearCustomData() {
      customData = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'resourceType' field.
      * @return The value.
      */
    public java.lang.String getResourceType() {
      return resourceType;
    }

    /**
      * Sets the value of the 'resourceType' field.
      * @param value The value of 'resourceType'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setResourceType(java.lang.String value) {
      validate(fields()[5], value);
      this.resourceType = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'resourceType' field has been set.
      * @return True if the 'resourceType' field has been set, false otherwise.
      */
    public boolean hasResourceType() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'resourceType' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearResourceType() {
      resourceType = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'hasChildren' field.
      * @return The value.
      */
    public java.lang.Integer getHasChildren() {
      return hasChildren;
    }

    /**
      * Sets the value of the 'hasChildren' field.
      * @param value The value of 'hasChildren'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setHasChildren(int value) {
      validate(fields()[6], value);
      this.hasChildren = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'hasChildren' field has been set.
      * @return True if the 'hasChildren' field has been set, false otherwise.
      */
    public boolean hasHasChildren() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'hasChildren' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearHasChildren() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'uuid' field.
      * @return The value.
      */
    public java.lang.String getUuid() {
      return uuid;
    }

    /**
      * Sets the value of the 'uuid' field.
      * @param value The value of 'uuid'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setUuid(java.lang.String value) {
      validate(fields()[7], value);
      this.uuid = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'uuid' field has been set.
      * @return True if the 'uuid' field has been set, false otherwise.
      */
    public boolean hasUuid() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'uuid' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastChanged' field.
      * @return The value.
      */
    public java.lang.Long getLastChanged() {
      return lastChanged;
    }

    /**
      * Sets the value of the 'lastChanged' field.
      * @param value The value of 'lastChanged'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setLastChanged(long value) {
      validate(fields()[8], value);
      this.lastChanged = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'lastChanged' field has been set.
      * @return True if the 'lastChanged' field has been set, false otherwise.
      */
    public boolean hasLastChanged() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'lastChanged' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearLastChanged() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'objectNotifiable' field.
      * @return The value.
      */
    public java.lang.Boolean getObjectNotifiable() {
      return objectNotifiable;
    }

    /**
      * Sets the value of the 'objectNotifiable' field.
      * @param value The value of 'objectNotifiable'.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder setObjectNotifiable(boolean value) {
      validate(fields()[9], value);
      this.objectNotifiable = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'objectNotifiable' field has been set.
      * @return True if the 'objectNotifiable' field has been set, false otherwise.
      */
    public boolean hasObjectNotifiable() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'objectNotifiable' field.
      * @return This builder.
      */
    public Energistics.Datatypes.Object.Resource.Builder clearObjectNotifiable() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    public Resource build() {
      try {
        Resource record = new Resource();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.String) defaultValue(fields()[0]);
        record.contentType = fieldSetFlags()[1] ? this.contentType : (java.lang.String) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.channelSubscribable = fieldSetFlags()[3] ? this.channelSubscribable : (java.lang.Boolean) defaultValue(fields()[3]);
        record.customData = fieldSetFlags()[4] ? this.customData : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[4]);
        record.resourceType = fieldSetFlags()[5] ? this.resourceType : (java.lang.String) defaultValue(fields()[5]);
        record.hasChildren = fieldSetFlags()[6] ? this.hasChildren : (java.lang.Integer) defaultValue(fields()[6]);
        record.uuid = fieldSetFlags()[7] ? this.uuid : (java.lang.String) defaultValue(fields()[7]);
        record.lastChanged = fieldSetFlags()[8] ? this.lastChanged : (java.lang.Long) defaultValue(fields()[8]);
        record.objectNotifiable = fieldSetFlags()[9] ? this.objectNotifiable : (java.lang.Boolean) defaultValue(fields()[9]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
