/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Energistics.Protocol.Core;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RenewSecurityToken extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4196861929127816628L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RenewSecurityToken\",\"namespace\":\"Energistics.Protocol.Core\",\"fields\":[{\"name\":\"token\",\"type\":\"string\"}],\"messageType\":\"6\",\"protocol\":\"0\",\"senderRole\":\"client\",\"protocolRoles\":\"client,server\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence token;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RenewSecurityToken() {}

  /**
   * All-args constructor.
   * @param token The new value for token
   */
  public RenewSecurityToken(java.lang.CharSequence token) {
    this.token = token;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return token;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: token = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'token' field.
   * @return The value of the 'token' field.
   */
  public java.lang.CharSequence getToken() {
    return token;
  }

  /**
   * Sets the value of the 'token' field.
   * @param value the value to set.
   */
  public void setToken(java.lang.CharSequence value) {
    this.token = value;
  }

  /**
   * Creates a new RenewSecurityToken RecordBuilder.
   * @return A new RenewSecurityToken RecordBuilder
   */
  public static Energistics.Protocol.Core.RenewSecurityToken.Builder newBuilder() {
    return new Energistics.Protocol.Core.RenewSecurityToken.Builder();
  }

  /**
   * Creates a new RenewSecurityToken RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RenewSecurityToken RecordBuilder
   */
  public static Energistics.Protocol.Core.RenewSecurityToken.Builder newBuilder(Energistics.Protocol.Core.RenewSecurityToken.Builder other) {
    return new Energistics.Protocol.Core.RenewSecurityToken.Builder(other);
  }

  /**
   * Creates a new RenewSecurityToken RecordBuilder by copying an existing RenewSecurityToken instance.
   * @param other The existing instance to copy.
   * @return A new RenewSecurityToken RecordBuilder
   */
  public static Energistics.Protocol.Core.RenewSecurityToken.Builder newBuilder(Energistics.Protocol.Core.RenewSecurityToken other) {
    return new Energistics.Protocol.Core.RenewSecurityToken.Builder(other);
  }

  /**
   * RecordBuilder for RenewSecurityToken instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RenewSecurityToken>
    implements org.apache.avro.data.RecordBuilder<RenewSecurityToken> {

    private java.lang.CharSequence token;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Energistics.Protocol.Core.RenewSecurityToken.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.token)) {
        this.token = data().deepCopy(fields()[0].schema(), other.token);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RenewSecurityToken instance
     * @param other The existing instance to copy.
     */
    private Builder(Energistics.Protocol.Core.RenewSecurityToken other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.token)) {
        this.token = data().deepCopy(fields()[0].schema(), other.token);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'token' field.
      * @return The value.
      */
    public java.lang.CharSequence getToken() {
      return token;
    }

    /**
      * Sets the value of the 'token' field.
      * @param value The value of 'token'.
      * @return This builder.
      */
    public Energistics.Protocol.Core.RenewSecurityToken.Builder setToken(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.token = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'token' field has been set.
      * @return True if the 'token' field has been set, false otherwise.
      */
    public boolean hasToken() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'token' field.
      * @return This builder.
      */
    public Energistics.Protocol.Core.RenewSecurityToken.Builder clearToken() {
      token = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public RenewSecurityToken build() {
      try {
        RenewSecurityToken record = new RenewSecurityToken();
        record.token = fieldSetFlags()[0] ? this.token : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
